# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 173)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calculate.setGeometry(QtCore.QRect(60, 80, 75, 23))
        self.btn_calculate.setObjectName("btn_calculate")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(10, 140, 391, 16))
        self.lbl_result.setText("")
        self.lbl_result.setObjectName("lbl_result")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 110, 491, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btn_calculate2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calculate2.setGeometry(QtCore.QRect(260, 80, 75, 23))
        self.btn_calculate2.setObjectName("btn_calculate2")
        self.date3 = QtWidgets.QDateEdit(self.centralwidget)
        self.date3.setGeometry(QtCore.QRect(250, 40, 110, 22))
        self.date3.setCalendarPopup(True)
        self.date3.setObjectName("date3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 170, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.date1 = QtWidgets.QDateEdit(self.widget)
        self.date1.setCalendarPopup(True)
        self.date1.setObjectName("date1")
        self.horizontalLayout.addWidget(self.date1)
        self.date2 = QtWidgets.QDateEdit(self.widget)
        self.date2.setObjectName("date2")
        self.horizontalLayout.addWidget(self.date2)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(20, 50, 173, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.time1 = QtWidgets.QTimeEdit(self.widget1)
        self.time1.setObjectName("time1")
        self.horizontalLayout_2.addWidget(self.time1)
        self.dateTime1 = QtWidgets.QDateTimeEdit(self.widget1)
        self.dateTime1.setCalendarPopup(True)
        self.dateTime1.setObjectName("dateTime1")
        self.horizontalLayout_2.addWidget(self.dateTime1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_calculate.setText(_translate("MainWindow", "Hesapla"))
        self.btn_calculate2.setText(_translate("MainWindow", "Hesapla 2"))
