# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 219)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableNodes = QtWidgets.QTableWidget(self.centralwidget)
        self.tableNodes.setGeometry(QtCore.QRect(20, 10, 256, 192))
        self.tableNodes.setObjectName("tableNodes")
        self.tableNodes.setColumnCount(0)
        self.tableNodes.setRowCount(0)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(290, 10, 225, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblNewNode = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblNewNode.setObjectName("lblNewNode")
        self.gridLayout.addWidget(self.lblNewNode, 0, 0, 1, 1)
        self.btnAddNewNode = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnAddNewNode.setObjectName("btnAddNewNode")
        self.gridLayout.addWidget(self.btnAddNewNode, 0, 3, 1, 1)
        self.txtNewNode = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtNewNode.setObjectName("txtNewNode")
        self.gridLayout.addWidget(self.txtNewNode, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblNewNode.setText(_translate("MainWindow", "New Node Value:"))
        self.btnAddNewNode.setText(_translate("MainWindow", "Add"))
