# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(411, 122)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_num1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_num1.setGeometry(QtCore.QRect(30, 10, 51, 21))
        self.lbl_num1.setObjectName("lbl_num1")
        self.lbl_num2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_num2.setGeometry(QtCore.QRect(30, 40, 51, 21))
        self.lbl_num2.setObjectName("lbl_num2")
        self.txtLine_num1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtLine_num1.setGeometry(QtCore.QRect(90, 10, 113, 20))
        self.txtLine_num1.setObjectName("txtLine_num1")
        self.txtLine_num2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtLine_num2.setGeometry(QtCore.QRect(90, 40, 113, 20))
        self.txtLine_num2.setObjectName("txtLine_num2")
        self.btn_sum = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sum.setGeometry(QtCore.QRect(220, 10, 75, 20))
        self.btn_sum.setObjectName("btn_sum")
        self.btn_diff = QtWidgets.QPushButton(self.centralwidget)
        self.btn_diff.setGeometry(QtCore.QRect(220, 40, 75, 20))
        self.btn_diff.setObjectName("btn_diff")
        self.btn_multi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_multi.setGeometry(QtCore.QRect(310, 10, 75, 20))
        self.btn_multi.setObjectName("btn_multi")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(310, 40, 75, 20))
        self.btn_div.setObjectName("btn_div")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(30, 90, 351, 16))
        self.lbl_result.setText("")
        self.lbl_result.setObjectName("lbl_result")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 70, 431, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 411, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_num1.setText(_translate("MainWindow", "Number 1:"))
        self.lbl_num2.setText(_translate("MainWindow", "Number 2:"))
        self.btn_sum.setText(_translate("MainWindow", "Sum"))
        self.btn_diff.setText(_translate("MainWindow", "Diff"))
        self.btn_multi.setText(_translate("MainWindow", "Multi"))
        self.btn_div.setText(_translate("MainWindow", "Division"))
