# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkboxes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(565, 304)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_get = QtWidgets.QPushButton(self.centralwidget)
        self.btn_get.setGeometry(QtCore.QRect(10, 220, 181, 23))
        self.btn_get.setObjectName("btn_get")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(200, 10, 351, 151))
        self.lbl_result.setText("")
        self.lbl_result.setObjectName("lbl_result")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 181, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_cinema = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_cinema.setObjectName("cb_cinema")
        self.verticalLayout.addWidget(self.cb_cinema)
        self.cb_book = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_book.setObjectName("cb_book")
        self.verticalLayout.addWidget(self.cb_book)
        self.cb_sport = QtWidgets.QCheckBox(self.layoutWidget)
        self.cb_sport.setObjectName("cb_sport")
        self.verticalLayout.addWidget(self.cb_sport)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 565, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_get.setText(_translate("MainWindow", "Seçilenleri Al"))
        self.cb_cinema.setText(_translate("MainWindow", "Sinema"))
        self.cb_book.setText(_translate("MainWindow", "Kitap Okumak"))
        self.cb_sport.setText(_translate("MainWindow", "Spor"))
