# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_radiobuttons.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(174, 254)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_select_country = QtWidgets.QLabel(self.centralwidget)
        self.lbl_select_country.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.lbl_select_country.setObjectName("lbl_select_country")
        self.widget_country = QtWidgets.QWidget(self.centralwidget)
        self.widget_country.setGeometry(QtCore.QRect(10, 30, 131, 101))
        self.widget_country.setObjectName("widget_country")
        self.radio_usa = QtWidgets.QRadioButton(self.widget_country)
        self.radio_usa.setGeometry(QtCore.QRect(0, 70, 82, 17))
        self.radio_usa.setObjectName("radio_usa")
        self.radio_turkey = QtWidgets.QRadioButton(self.widget_country)
        self.radio_turkey.setGeometry(QtCore.QRect(0, 10, 82, 17))
        self.radio_turkey.setObjectName("radio_turkey")
        self.radio_germany = QtWidgets.QRadioButton(self.widget_country)
        self.radio_germany.setGeometry(QtCore.QRect(0, 40, 82, 17))
        self.radio_germany.setAutoExclusive(True)
        self.radio_germany.setObjectName("radio_germany")
        self.btn_get = QtWidgets.QPushButton(self.centralwidget)
        self.btn_get.setGeometry(QtCore.QRect(10, 140, 75, 23))
        self.btn_get.setObjectName("btn_get")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(10, 190, 151, 16))
        self.lbl_result.setObjectName("lbl_result")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 170, 201, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(90, 140, 75, 23))
        self.btn_clear.setObjectName("btn_clear")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_select_country.setText(_translate("MainWindow", "Ülkenizi seçiniz."))
        self.radio_usa.setText(_translate("MainWindow", "Amerika"))
        self.radio_turkey.setText(_translate("MainWindow", "Türkiye"))
        self.radio_germany.setText(_translate("MainWindow", "Almanya"))
        self.btn_get.setText(_translate("MainWindow", "Seçileni Al"))
        self.lbl_result.setText(_translate("MainWindow", "Ülkeniz:"))
        self.btn_clear.setText(_translate("MainWindow", "Temizle"))
