# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 295)
        MainWindow.setMinimumSize(QtCore.QSize(461, 295))
        MainWindow.setMaximumSize(QtCore.QSize(461, 295))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 20, 256, 251))
        self.listWidget.setObjectName("listWidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(326, 22, 121, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_add = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout.addWidget(self.btn_add)
        self.btn_edit = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_edit.setObjectName("btn_edit")
        self.verticalLayout.addWidget(self.btn_edit)
        self.btn_remove = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_remove.setObjectName("btn_remove")
        self.verticalLayout.addWidget(self.btn_remove)
        self.btn_up = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_up.setObjectName("btn_up")
        self.verticalLayout.addWidget(self.btn_up)
        self.btn_down = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_down.setObjectName("btn_down")
        self.verticalLayout.addWidget(self.btn_down)
        self.btn_sort = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_sort.setObjectName("btn_sort")
        self.verticalLayout.addWidget(self.btn_sort)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_exit = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_add.setText(_translate("MainWindow", "Add"))
        self.btn_edit.setText(_translate("MainWindow", "Edit"))
        self.btn_remove.setText(_translate("MainWindow", "Remove"))
        self.btn_up.setText(_translate("MainWindow", "Up"))
        self.btn_down.setText(_translate("MainWindow", "Down"))
        self.btn_sort.setText(_translate("MainWindow", "Sort"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))
