# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_comboboxes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(293, 179)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.combo_cities = QtWidgets.QComboBox(self.centralwidget)
        self.combo_cities.setGeometry(QtCore.QRect(20, 40, 71, 22))
        self.combo_cities.setObjectName("combo_cities")
        self.btn_get = QtWidgets.QPushButton(self.centralwidget)
        self.btn_get.setGeometry(QtCore.QRect(20, 70, 71, 23))
        self.btn_get.setObjectName("btn_get")
        self.lbl_select_city = QtWidgets.QLabel(self.centralwidget)
        self.lbl_select_city.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.lbl_select_city.setObjectName("lbl_select_city")
        self.txt_load = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_load.setGeometry(QtCore.QRect(120, 30, 113, 20))
        self.txt_load.setObjectName("txt_load")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(20, 150, 261, 16))
        self.lbl_result.setText("")
        self.lbl_result.setObjectName("lbl_result")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 130, 311, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(120, 60, 160, 75))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_load = QtWidgets.QPushButton(self.widget)
        self.btn_load.setObjectName("btn_load")
        self.horizontalLayout.addWidget(self.btn_load)
        self.btn_delete = QtWidgets.QPushButton(self.widget)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn_delete_all = QtWidgets.QPushButton(self.widget)
        self.btn_delete_all.setObjectName("btn_delete_all")
        self.verticalLayout.addWidget(self.btn_delete_all)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_get.setText(_translate("MainWindow", "Seçileni Al"))
        self.lbl_select_city.setText(_translate("MainWindow", "Şehir seçiniz."))
        self.btn_load.setText(_translate("MainWindow", "Yükle"))
        self.btn_delete.setText(_translate("MainWindow", "Sil"))
        self.btn_delete_all.setText(_translate("MainWindow", "Hepsini Sil"))
