# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(515, 437)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableProducts = QtWidgets.QTableWidget(self.centralwidget)
        self.tableProducts.setGeometry(QtCore.QRect(20, 30, 211, 371))
        self.tableProducts.setObjectName("tableProducts")
        self.tableProducts.setColumnCount(0)
        self.tableProducts.setRowCount(0)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(240, 30, 196, 83))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lblName = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblName.setObjectName("lblName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblName)
        self.txt_lineName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_lineName.setObjectName("txt_lineName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_lineName)
        self.txt_lineGender = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_lineGender.setObjectName("txt_lineGender")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_lineGender)
        self.lblGender = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblGender.setObjectName("lblGender")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblGender)
        self.btnSave = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnSave.setObjectName("btnSave")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnSave)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblName.setText(_translate("MainWindow", "Name"))
        self.lblGender.setText(_translate("MainWindow", "Gender"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
